# Generated by Django 3.2.7 on 2021-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210925_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('middlename', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('cust_name', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('mail', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('cust_create_date', models.DateField()),
            ],
        ),
    ]
